---
title: "> mohamed"
author: Mohamed Elg
email: ""
url: https://mohamed-elg.github.io
baseurl: "/"
description: >
  <p>  <br>  Mohamed EL GUERMAT <br>  DevOps Engineer <br> Paris, France <br> <br> Technologies: Python, Linux, Git, Docker, Kubernetes, AWS, Terraform <br> <br> Interests: programming, reading, Chess, the piano <br> </p> <br>

permalink: /:slug.html

favicon: "assets/images/favicon.png"
goat_counter: "mohamed-elg"
remote_theme: riggraz/no-style-please

theme_config:
  appearance: "dark"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%d-%m-%Y"
  show_description: true

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  reco:
    output: false
